apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config2
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: kubernetes.io/metadata.name=loibiscom
  namespace: default
data:
  key1: value1
  key2: value2
  key3: value3


